language: android
jdk: oraclejdk8
sudo: false

env:
  global:
  - ANDROID_API=27
  - EMULATOR_API=24
  - ANDROID_BUILD_TOOLS=27.0.3

 "os": "linux"


android:
  components:
  - tools
#  - android-$EMULATOR_API
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

notifications:
  email: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - chmod +x gradlew
  - "./gradlew --quiet androidGitVersion"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew lintRelease publishRelease; else ./gradlew lintRelease test; fi

before_install:
- yes | sdkmanager "platforms;android-27"
- openssl aes-256-cbc -K $encrypted_12e8842891a3_key -iv $encrypted_12e8842891a3_iv
  -in files/kau.tar.enc -out kau.tar -d
- tar xvf kau.tar

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew build connectedCheck
  - ./gradlew connectedAndroidTest


after_success:
  - bash <(curl -s https://codecov.io/bash)

